Repository glados-FunChill/glados, pull requests merged in 2025-01, with the labels that each got.

#15 Add first definition of grammar
  docs/grammar/grammar.peg
Labels: documentation, enhancement

#19 Update dependencies
  flake.lock
  flake.nix
  stack.yaml
  stack.yaml.lock
Labels: enhancement

#13 Call operator hotfix
  .github/workflows/actions.yml
  src/Lib.hs
Labels: bug

#20 Release 1.1
  .github/workflows/actions.yml
  src/Lib.hs
Labels: bug

#23 Quick parser fixes
  src/Helpers.hs
  src/Parser/Internal2.hs
  src/Parser/Shorthands.hs
  src/Parser2.hs
  test/ParserSpec.hs
Labels: enhancement

#37 Combined main
  .gitignore
  GLaDOS.cabal
  Makefile
  app/Compiler.hs
  app/Main-all.hs
  app/Main-cmp.hs
  app/Main-exe.hs
  app/VM.hs
  package.yaml
Labels: enhancement

#41 Use Data.Text in VM and bytecode
  src/ConvertASTtoInstructions.hs
  src/GldsBytecode.hs
  src/StackMachine.hs
  test/CompilerSpec.hs
  test/VmSpec.hs
Labels: enhancement

#40 Disassembler
  GLaDOS.cabal
  app/Main-all.hs
  app/VM.hs
  package.yaml
  src/Disassembly.hs
  src/GldsBytecode.hs
  src/Helpers.hs
Labels: enhancement

#42 Fix function call arguments
  src/Helpers.hs
  src/StackMachine.hs
Labels: enhancement

#36 For Loops
  docs/grammar/grammar.peg
  docs/language-doc/docs/reference/expressions.md
  docs/language-doc/docs/reference/keywords.md
  src/ConvertASTtoInstructions.hs
  src/Lexer.x
  src/Lexer/Tokens.hs
  src/Parser.hs
  src/Parser/AST.hs
  src/Parser/Shorthands.hs
  test/CompilerSpec.hs
  test/ParserSpec.hs
  test/VmSpec.hs
Labels: enhancement

#46 Parser error display
  app/Compiler.hs
  src/AlexToParsec.hs
  src/Lexer.x
  src/Parser.hs
  src/Parser/ParseAndLex.hs
  test/ParserSpec.hs
Labels: enhancement

#51 Run module
  GLaDOS.cabal
  app/Compiler.hs
  app/Main-all.hs
  app/Run.hs
  src/StackMachine.hs
Labels: enhancement

#54 Require end of file
  Makefile
  src/Parser.hs
  test/functional_tests/cases/fail_with_trailing_exprs/exit
  test/functional_tests/cases/fail_with_trailing_exprs/in
  test/functional_tests/cases/fail_with_trailing_exprs/out
  test/functional_tests/cases/iterative_factorial/in
  test/functional_tests/cases/iterative_factorial/out
  test/functional_tests/cases/recusive_factorial/in
  test/functional_tests/cases/recusive_factorial/out
  test/functional_tests/cases/return_0/in
  test/functional_tests/cases/return_0/out
  test/functional_tests/tester.sh
Labels: bug
